update_meta "rmw_microxrcedds" "RMW_UXRCE_MAX_NODES=1"
update_meta "rmw_microxrcedds" "RMW_UXRCE_MAX_PUBLISHERS=1"
update_meta "rmw_microxrcedds" "RMW_UXRCE_MAX_SUBSCRIPTIONS=0"
update_meta "rmw_microxrcedds" "RMW_UXRCE_MAX_SERVICES=1"
update_meta "rmw_microxrcedds" "RMW_UXRCE_MAX_CLIENTS=0"
update_meta "rmw_microxrcedds" "RMW_UXRCE_MAX_HISTORY=4"